-- begin SYS_SCHEDULED_EXECUTION
alter table SYS_SCHEDULED_EXECUTION add constraint FK_SYS_SCHEDEXECU_ON_TASK foreign key (TASK_ID) references SYS_SCHEDULED_TASK(ID)^
create index IDX_SYS_SCHEEXEC_ON_TASK on SYS_SCHEDULED_EXECUTION (TASK_ID)^

-- end SYS_SCHEDULED_EXECUTION
-- begin SEC_LOGGED_ATTR
alter table SEC_LOGGED_ATTR add constraint FK_SEC_LOGGED_ATTR_ON_ENTITY foreign key (ENTITY_ID) references SEC_LOGGED_ENTITY(ID)^
create index IDX_SEC_LOGGED_ATTR_ON_ENTITY on SEC_LOGGED_ATTR (ENTITY_ID)^

-- end SEC_LOGGED_ATTR
-- begin SEC_GROUP
alter table SEC_GROUP add constraint FK_SEC_GROUP_ON_PARENT foreign key (PARENT_ID) references SEC_GROUP(ID)^
create index IDX_SEC_GROUP_ON_PARENT on SEC_GROUP (PARENT_ID)^

-- end SEC_GROUP
-- begin SYS_FOLDER
alter table SYS_FOLDER add constraint FK_SYS_FOLDER_ON_PARENT foreign key (PARENT_ID) references SYS_FOLDER(ID)^
create index IDX_SYS_FOLDER_ON_PARENT on SYS_FOLDER (PARENT_ID)^

-- end SYS_FOLDER
-- begin SEC_GROUP_HIERARCHY
alter table SEC_GROUP_HIERARCHY add constraint FK_SEC_GROUPHIERA_ON_GROUP foreign key (GROUP_ID) references SEC_GROUP(ID)^
alter table SEC_GROUP_HIERARCHY add constraint FK_SEC_GROUPHIERA_ON_PARENT foreign key (PARENT_ID) references SEC_GROUP(ID)^
create index IDX_SEC_GROUHIER_ON_GROUP on SEC_GROUP_HIERARCHY (GROUP_ID)^
create index IDX_SEC_GROUHIER_ON_PARENT on SEC_GROUP_HIERARCHY (PARENT_ID)^

-- end SEC_GROUP_HIERARCHY
-- begin SEC_CONSTRAINT
alter table SEC_CONSTRAINT add constraint FK_SEC_CONSTRAINT_ON_GROUP foreign key (GROUP_ID) references SEC_GROUP(ID)^
create index IDX_SEC_CONSTRAINT_ON_GROUP on SEC_CONSTRAINT (GROUP_ID)^

-- end SEC_CONSTRAINT
-- begin SYS_APP_FOLDER
alter table SYS_APP_FOLDER add constraint FK_SYS_APP_FOLDER_ON_FOLDER foreign key (FOLDER_ID) references SYS_FOLDER(ID) on delete CASCADE^

-- end SYS_APP_FOLDER
-- begin SYS_ENTITY_SNAPSHOT
alter table SYS_ENTITY_SNAPSHOT add constraint FK_SYS_ENTITSNAPS_ON_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID)^
create index IDX_SYS_ENTISNAP_ON_AUTHOR on SYS_ENTITY_SNAPSHOT (AUTHOR_ID)^

-- end SYS_ENTITY_SNAPSHOT
-- begin SYS_CATEGORY_ATTR
alter table SYS_CATEGORY_ATTR add constraint FK_SYS_CATEGATTR_ON_CATEGORY foreign key (CATEGORY_ID) references SYS_CATEGORY(ID)^
create index IDX_SYS_CATEATTR_ON_CATEGORY on SYS_CATEGORY_ATTR (CATEGORY_ID)^

-- end SYS_CATEGORY_ATTR
-- begin SEC_REMEMBER_ME
alter table SEC_REMEMBER_ME add constraint FK_SEC_REMEMBER_ME_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SEC_REMEMBER_ME_ON_USER on SEC_REMEMBER_ME (USER_ID)^

-- end SEC_REMEMBER_ME
-- begin SYS_ATTR_VALUE
alter table SYS_ATTR_VALUE add constraint FK_SYS_ATTRVALU_ON_CATEATTR foreign key (CATEGORY_ATTR_ID) references SYS_CATEGORY_ATTR(ID)^
alter table SYS_ATTR_VALUE add constraint FK_SYS_ATTR_VALUE_ON_PARENT foreign key (PARENT_ID) references SYS_ATTR_VALUE(ID)^
create index IDX_SYS_ATTVAL_ON_CATATT on SYS_ATTR_VALUE (CATEGORY_ATTR_ID)^
create index IDX_SYS_ATTR_VALUE_ON_PARENT on SYS_ATTR_VALUE (PARENT_ID)^

-- end SYS_ATTR_VALUE
-- begin SEC_FILTER
alter table SEC_FILTER add constraint FK_SEC_FILTER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SEC_FILTER_ON_USER on SEC_FILTER (USER_ID)^

-- end SEC_FILTER
-- begin SYS_SENDING_MESSAGE
alter table SYS_SENDING_MESSAGE add constraint FK_SYS_SENMES_ON_CONTEXFIL foreign key (CONTENT_TEXT_FILE_ID) references SYS_FILE(ID)^
create index IDX_SYS_SENMES_ON_CONTEXFIL on SYS_SENDING_MESSAGE (CONTENT_TEXT_FILE_ID)^

-- end SYS_SENDING_MESSAGE
-- begin SEC_SCREEN_HISTORY
alter table SEC_SCREEN_HISTORY add constraint FK_SEC_SCREEN_HISTORY_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table SEC_SCREEN_HISTORY add constraint FK_SEC_SCREHIST_ON_SUBSUSER foreign key (SUBSTITUTED_USER_ID) references SEC_USER(ID)^
create index IDX_SEC_SCREHIST_ON_USER on SEC_SCREEN_HISTORY (USER_ID)^
create index IDX_SEC_SCRHIS_ON_SUBUSE on SEC_SCREEN_HISTORY (SUBSTITUTED_USER_ID)^

-- end SEC_SCREEN_HISTORY
-- begin SEC_ENTITY_LOG
alter table SEC_ENTITY_LOG add constraint FK_SEC_ENTITY_LOG_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SEC_ENTITY_LOG_ON_USER on SEC_ENTITY_LOG (USER_ID)^

-- end SEC_ENTITY_LOG
-- begin SEC_PRESENTATION
alter table SEC_PRESENTATION add constraint FK_SEC_PRESENTATION_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SEC_PRESENTATION_ON_USER on SEC_PRESENTATION (USER_ID)^

-- end SEC_PRESENTATION
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_GROUP foreign key (GROUP_ID) references SEC_GROUP(ID)^
create index IDX_SEC_USER_ON_GROUP on SEC_USER (GROUP_ID)^

-- end SEC_USER
-- begin SEC_USER_SETTING
alter table SEC_USER_SETTING add constraint FK_SEC_USER_SETTING_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SEC_USER_SETTING_ON_USER on SEC_USER_SETTING (USER_ID)^

-- end SEC_USER_SETTING
-- begin SEC_SEARCH_FOLDER
alter table SEC_SEARCH_FOLDER add constraint FK_SEC_SEARCH_FOLDER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table SEC_SEARCH_FOLDER add constraint FK_SEC_SEARCFOLDE_ON_PRESE foreign key (PRESENTATION_ID) references SEC_PRESENTATION(ID)^
alter table SEC_SEARCH_FOLDER add constraint FK_SEC_SEARCFOLDE_ON_FOLDER foreign key (FOLDER_ID) references SYS_FOLDER(ID) on delete CASCADE^
create index IDX_SEC_SEARCH_FOLDER_ON_USER on SEC_SEARCH_FOLDER (USER_ID)^
create index IDX_SEC_SEARFOLD_ON_PRES on SEC_SEARCH_FOLDER (PRESENTATION_ID)^

-- end SEC_SEARCH_FOLDER
-- begin SYS_SENDING_ATTACHMENT
alter table SYS_SENDING_ATTACHMENT add constraint FK_SYS_SENDIATTAC_ON_MESSAGE foreign key (MESSAGE_ID) references SYS_SENDING_MESSAGE(ID)^
alter table SYS_SENDING_ATTACHMENT add constraint FK_SYS_SENDATTA_ON_CONTFILE foreign key (CONTENT_FILE_ID) references SYS_FILE(ID)^
create index IDX_SYS_SENDATTA_ON_MESSAGE on SYS_SENDING_ATTACHMENT (MESSAGE_ID)^
create index IDX_SYS_SENATT_ON_CONFIL on SYS_SENDING_ATTACHMENT (CONTENT_FILE_ID)^

-- end SYS_SENDING_ATTACHMENT
-- begin SEC_PERMISSION
alter table SEC_PERMISSION add constraint FK_SEC_PERMISSION_ON_ROLE foreign key (ROLE_ID) references SEC_ROLE(ID)^
create index IDX_SEC_PERMISSION_ON_ROLE on SEC_PERMISSION (ROLE_ID)^

-- end SEC_PERMISSION
-- begin SEC_USER_SUBSTITUTION
alter table SEC_USER_SUBSTITUTION add constraint FK_SEC_USERSUBST_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table SEC_USER_SUBSTITUTION add constraint FK_SEC_USERSUBS_ON_SUBSUSER foreign key (SUBSTITUTED_USER_ID) references SEC_USER(ID)^
create index IDX_SEC_USERSUBS_ON_USER on SEC_USER_SUBSTITUTION (USER_ID)^
create index IDX_SEC_USESUB_ON_SUBUSE on SEC_USER_SUBSTITUTION (SUBSTITUTED_USER_ID)^

-- end SEC_USER_SUBSTITUTION
-- begin SEC_SESSION_LOG
alter table SEC_SESSION_LOG add constraint FK_SEC_SESSLOG_ON_SUBSUSER foreign key (SUBSTITUTED_USER_ID) references SEC_USER(ID)^
alter table SEC_SESSION_LOG add constraint FK_SEC_SESSION_LOG_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SEC_SESLOG_ON_SUBUSE on SEC_SESSION_LOG (SUBSTITUTED_USER_ID)^
create index IDX_SEC_SESSION_LOG_ON_USER on SEC_SESSION_LOG (USER_ID)^

-- end SEC_SESSION_LOG
-- begin SEC_USER_ROLE
alter table SEC_USER_ROLE add constraint FK_SEC_USER_ROLE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table SEC_USER_ROLE add constraint FK_SEC_USER_ROLE_ON_ROLE foreign key (ROLE_ID) references SEC_ROLE(ID)^
create index IDX_SEC_USER_ROLE_ON_USER on SEC_USER_ROLE (USER_ID)^
create index IDX_SEC_USER_ROLE_ON_ROLE on SEC_USER_ROLE (ROLE_ID)^

-- end SEC_USER_ROLE
-- begin SEC_SESSION_ATTR
alter table SEC_SESSION_ATTR add constraint FK_SEC_SESSION_ATTR_ON_GROUP foreign key (GROUP_ID) references SEC_GROUP(ID)^
create index IDX_SEC_SESSION_ATTR_ON_GROUP on SEC_SESSION_ATTR (GROUP_ID)^

-- end SEC_SESSION_ATTR
