-- begin SYS_SCHEDULED_EXECUTION
alter table SYS_SCHEDULED_EXECUTION add constraint FK_SYS_SCHEDULEXECUTI_TASK foreign key (TASK_ID) references SYS_SCHEDULED_TASK(ID)^
create index IDX_SYS_SCHEDUEXECUT_TASK on SYS_SCHEDULED_EXECUTION (TASK_ID)^

-- end SYS_SCHEDULED_EXECUTION
-- begin SEC_LOGGED_ATTR
alter table SEC_LOGGED_ATTR add constraint FK_SEC_LOGGED_ATTR_ENTITY foreign key (ENTITY_ID) references SEC_LOGGED_ENTITY(ID)^
create index IDX_SEC_LOGGED_ATTR_ENTITY on SEC_LOGGED_ATTR (ENTITY_ID)^

-- end SEC_LOGGED_ATTR
-- begin SEC_GROUP
alter table SEC_GROUP add constraint FK_SEC_GROUP_PARENT foreign key (PARENT_ID) references SEC_GROUP(ID)^
create index IDX_SEC_GROUP_PARENT on SEC_GROUP (PARENT_ID)^

-- end SEC_GROUP
-- begin SYS_FOLDER
alter table SYS_FOLDER add constraint FK_SYS_FOLDER_PARENT foreign key (PARENT_ID) references SYS_FOLDER(ID)^
create index IDX_SYS_FOLDER_PARENT on SYS_FOLDER (PARENT_ID)^

-- end SYS_FOLDER
-- begin SEC_GROUP_HIERARCHY
alter table SEC_GROUP_HIERARCHY add constraint FK_SEC_GROUP_HIERARCHY_GROUP foreign key (GROUP_ID) references SEC_GROUP(ID)^
alter table SEC_GROUP_HIERARCHY add constraint FK_SEC_GROUP_HIERARCHY_PARENT foreign key (PARENT_ID) references SEC_GROUP(ID)^
create index IDX_SEC_GROUP_HIERARCHY_GROUP on SEC_GROUP_HIERARCHY (GROUP_ID)^
create index IDX_SEC_GROUPHIERAR_PARENT on SEC_GROUP_HIERARCHY (PARENT_ID)^

-- end SEC_GROUP_HIERARCHY
-- begin SEC_CONSTRAINT
alter table SEC_CONSTRAINT add constraint FK_SEC_CONSTRAINT_GROUP foreign key (GROUP_ID) references SEC_GROUP(ID)^
create index IDX_SEC_CONSTRAINT_GROUP on SEC_CONSTRAINT (GROUP_ID)^

-- end SEC_CONSTRAINT
-- begin SYS_APP_FOLDER
alter table SYS_APP_FOLDER add constraint FK_SYS_APP_FOLDER_FOLDER foreign key (FOLDER_ID) references SYS_FOLDER(ID)^

-- end SYS_APP_FOLDER
-- begin SYS_ENTITY_SNAPSHOT
alter table SYS_ENTITY_SNAPSHOT add constraint FK_SYS_ENTITY_SNAPSHOT_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID)^
create index IDX_SYS_ENTITYSNAPSH_AUTHOR on SYS_ENTITY_SNAPSHOT (AUTHOR_ID)^

-- end SYS_ENTITY_SNAPSHOT
-- begin SYS_CATEGORY_ATTR
alter table SYS_CATEGORY_ATTR add constraint FK_SYS_CATEGORY_ATTR_CATEGORY foreign key (CATEGORY_ID) references SYS_CATEGORY(ID)^
create index IDX_SYS_CATEGOATTR_CATEGORY on SYS_CATEGORY_ATTR (CATEGORY_ID)^

-- end SYS_CATEGORY_ATTR
-- begin SEC_REMEMBER_ME
alter table SEC_REMEMBER_ME add constraint FK_SEC_REMEMBER_ME_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SEC_REMEMBER_ME_USER on SEC_REMEMBER_ME (USER_ID)^

-- end SEC_REMEMBER_ME
-- begin SYS_ATTR_VALUE
alter table SYS_ATTR_VALUE add constraint FK_SYS_ATTRVALUE_CATEGATTR foreign key (CATEGORY_ATTR_ID) references SYS_CATEGORY_ATTR(ID)^
alter table SYS_ATTR_VALUE add constraint FK_SYS_ATTR_VALUE_PARENT foreign key (PARENT_ID) references SYS_ATTR_VALUE(ID)^
create index IDX_SYS_ATTRVALUE_CATEGATTR on SYS_ATTR_VALUE (CATEGORY_ATTR_ID)^
create index IDX_SYS_ATTR_VALUE_PARENT on SYS_ATTR_VALUE (PARENT_ID)^

-- end SYS_ATTR_VALUE
-- begin SEC_FILTER
alter table SEC_FILTER add constraint FK_SEC_FILTER_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SEC_FILTER_USER on SEC_FILTER (USER_ID)^

-- end SEC_FILTER
-- begin SYS_SENDING_MESSAGE
alter table SYS_SENDING_MESSAGE add constraint FK_SYS_SENDMESS_CONTTEXTFILE foreign key (CONTENT_TEXT_FILE_ID) references SYS_FILE(ID)^

-- end SYS_SENDING_MESSAGE
-- begin SEC_SCREEN_HISTORY
alter table SEC_SCREEN_HISTORY add constraint FK_SEC_SCREEN_HISTORY_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table SEC_SCREEN_HISTORY add constraint FK_SEC_SCREEHISTO_SUBSTUSER foreign key (SUBSTITUTED_USER_ID) references SEC_USER(ID)^
create index IDX_SEC_SCREEN_HISTORY_USER on SEC_SCREEN_HISTORY (USER_ID)^
create index IDX_SEC_SCREEHISTO_SUBSTUSER on SEC_SCREEN_HISTORY (SUBSTITUTED_USER_ID)^

-- end SEC_SCREEN_HISTORY
-- begin SEC_PRESENTATION
alter table SEC_PRESENTATION add constraint FK_SEC_PRESENTATION_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SEC_PRESENTATION_USER on SEC_PRESENTATION (USER_ID)^

-- end SEC_PRESENTATION
-- begin SEC_ENTITY_LOG
alter table SEC_ENTITY_LOG add constraint FK_SEC_ENTITY_LOG_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SEC_ENTITY_LOG_USER on SEC_ENTITY_LOG (USER_ID)^

-- end SEC_ENTITY_LOG
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_GROUP foreign key (GROUP_ID) references SEC_GROUP(ID)^
create index IDX_SEC_USER_GROUP on SEC_USER (GROUP_ID)^

-- end SEC_USER
-- begin SEC_USER_SETTING
alter table SEC_USER_SETTING add constraint FK_SEC_USER_SETTING_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SEC_USER_SETTING_USER on SEC_USER_SETTING (USER_ID)^

-- end SEC_USER_SETTING
-- begin SEC_SEARCH_FOLDER
alter table SEC_SEARCH_FOLDER add constraint FK_SEC_SEARCH_FOLDER_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table SEC_SEARCH_FOLDER add constraint FK_SEC_SEARCHFOLDER_PRESENT foreign key (PRESENTATION_ID) references SEC_PRESENTATION(ID)^
alter table SEC_SEARCH_FOLDER add constraint FK_SEC_SEARCH_FOLDER_FOLDER foreign key (FOLDER_ID) references SYS_FOLDER(ID)^
create index IDX_SEC_SEARCH_FOLDER_USER on SEC_SEARCH_FOLDER (USER_ID)^
create index IDX_SEC_SEARCHFOLDER_PRESEN on SEC_SEARCH_FOLDER (PRESENTATION_ID)^

-- end SEC_SEARCH_FOLDER
-- begin SYS_SENDING_ATTACHMENT
alter table SYS_SENDING_ATTACHMENT add constraint FK_SYS_SENDINGATTACHM_MESSAGE foreign key (MESSAGE_ID) references SYS_SENDING_MESSAGE(ID)^
alter table SYS_SENDING_ATTACHMENT add constraint FK_SYS_SENDIATTAC_CONTEFILE foreign key (CONTENT_FILE_ID) references SYS_FILE(ID)^
create index IDX_SYS_SENDINATTACH_MESSAGE on SYS_SENDING_ATTACHMENT (MESSAGE_ID)^

-- end SYS_SENDING_ATTACHMENT
-- begin SEC_PERMISSION
alter table SEC_PERMISSION add constraint FK_SEC_PERMISSION_ROLE foreign key (ROLE_ID) references SEC_ROLE(ID)^
create index IDX_SEC_PERMISSION_ROLE on SEC_PERMISSION (ROLE_ID)^

-- end SEC_PERMISSION
-- begin SEC_USER_SUBSTITUTION
alter table SEC_USER_SUBSTITUTION add constraint FK_SEC_USER_SUBSTITUTION_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table SEC_USER_SUBSTITUTION add constraint FK_SEC_USERSUBST_SUBSTUSER foreign key (SUBSTITUTED_USER_ID) references SEC_USER(ID)^
create index IDX_SEC_USERSUBSTI_USER on SEC_USER_SUBSTITUTION (USER_ID)^
create index IDX_SEC_USERSUBST_SUBSTUSER on SEC_USER_SUBSTITUTION (SUBSTITUTED_USER_ID)^

-- end SEC_USER_SUBSTITUTION
-- begin SEC_SESSION_LOG
alter table SEC_SESSION_LOG add constraint FK_SEC_SESSILOG_SUBSTUSER foreign key (SUBSTITUTED_USER_ID) references SEC_USER(ID)^
alter table SEC_SESSION_LOG add constraint FK_SEC_SESSION_LOG_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SEC_SESSILOG_SUBSTUSER on SEC_SESSION_LOG (SUBSTITUTED_USER_ID)^
create index IDX_SEC_SESSION_LOG_USER on SEC_SESSION_LOG (USER_ID)^

-- end SEC_SESSION_LOG
-- begin SEC_USER_ROLE
alter table SEC_USER_ROLE add constraint FK_SEC_USER_ROLE_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table SEC_USER_ROLE add constraint FK_SEC_USER_ROLE_ROLE foreign key (ROLE_ID) references SEC_ROLE(ID)^
create index IDX_SEC_USER_ROLE_USER on SEC_USER_ROLE (USER_ID)^
create index IDX_SEC_USER_ROLE_ROLE on SEC_USER_ROLE (ROLE_ID)^

-- end SEC_USER_ROLE
-- begin SEC_SESSION_ATTR
alter table SEC_SESSION_ATTR add constraint FK_SEC_SESSION_ATTR_GROUP foreign key (GROUP_ID) references SEC_GROUP(ID)^
create index IDX_SEC_SESSION_ATTR_GROUP on SEC_SESSION_ATTR (GROUP_ID)^

-- end SEC_SESSION_ATTR
